version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - storage:/app/storage
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

volumes:
  storage:
